-- =========================================================================
-- SCRIPT SQL: ESTRUCTURA PARA MÓDULO WMS / INVENTARIO DE BODEGAS Y OBSERVACIONES
-- Ejecuta este script en el Editor SQL de tu proyecto Supabase:
-- https://supabase.com/dashboard/project/plsvbuzcjtztpidsjmua/sql
-- =========================================================================

-- 1. Asegurar tabla de Observaciones e Inspecciones de Bodega
CREATE TABLE IF NOT EXISTS warehouse_observations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  warehouse_id UUID REFERENCES warehouses(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  observacion TEXT NOT NULL,
  categoria TEXT DEFAULT 'Inspección General', -- 'Inspección General', 'Novedad de Stock', 'Mantenimiento', 'Auditoría', 'Seguridad'
  nivel_alerta TEXT DEFAULT 'Normal' CHECK (nivel_alerta IN ('Normal', 'Advertencia', 'Crítico')),
  estado TEXT DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'En Revisión', 'Resuelto')),
  usuario_email TEXT,
  responsable TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Asegurar tabla de Transferencias Inter-Bodega
CREATE TABLE IF NOT EXISTS inventory_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  consecutive INTEGER GENERATED BY DEFAULT AS IDENTITY,
  orig_warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT,
  dest_warehouse_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT,
  estado TEXT NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Borrador', 'Pendiente', 'Aprobado', 'En Tránsito', 'Recibido', 'Rechazado', 'Anulado')),
  solicitado_por TEXT,
  aprobado_por TEXT,
  recibido_por TEXT,
  observaciones TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Asegurar tabla de Conteos Físicos de Inventario
CREATE TABLE IF NOT EXISTS inventory_counts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  consecutive INTEGER GENERATED BY DEFAULT AS IDENTITY,
  warehouse_id UUID REFERENCES warehouses(id) ON DELETE CASCADE,
  nombre_conteo TEXT NOT NULL,
  estado TEXT DEFAULT 'En Proceso' CHECK (estado IN ('Borrador', 'En Proceso', 'Sometido', 'Aprobado', 'Rechazado')),
  realizado_por TEXT,
  aprobado_por TEXT,
  diferencia_unidades INTEGER DEFAULT 0,
  diferencia_valor NUMERIC DEFAULT 0,
  observaciones TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Detalle del conteo físico
CREATE TABLE IF NOT EXISTS inventory_count_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  count_id UUID REFERENCES inventory_counts(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  color_id UUID REFERENCES colors(id) ON DELETE SET NULL,
  size_id UUID REFERENCES sizes(id) ON DELETE SET NULL,
  cantidad_sistema INTEGER NOT NULL DEFAULT 0,
  cantidad_fisica INTEGER NOT NULL DEFAULT 0,
  diferencia INTEGER GENERATED ALWAYS AS (cantidad_fisica - cantidad_sistema) STORED,
  costo_unitario NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Habilitar Seguridad RLS y Permisos
ALTER TABLE warehouse_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_count_items ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'warehouse_observations' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON warehouse_observations FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'inventory_transfers' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON inventory_transfers FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'inventory_counts' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON inventory_counts FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'inventory_count_items' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON inventory_count_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

GRANT ALL ON warehouse_observations TO authenticated;
GRANT ALL ON inventory_transfers TO authenticated;
GRANT ALL ON inventory_counts TO authenticated;
GRANT ALL ON inventory_count_items TO authenticated;

GRANT SELECT ON warehouse_observations TO anon;
GRANT SELECT ON inventory_transfers TO anon;
GRANT SELECT ON inventory_counts TO anon;
GRANT SELECT ON inventory_count_items TO anon;

-- Notificar recarga de caché Schema PostgREST
NOTIFY pgrst, 'reload schema';
