-- =========================================================================
-- SCRIPT SQL: ESTRUCTURA COMPLETA PARA MÓDULO DE AUDITORÍA Y CONTROL BREINER AUDIT
-- Ejecuta este script en el Editor SQL de tu proyecto Supabase
-- =========================================================================

-- 1. Tabla de Sesiones de Auditoría (Fábrica, Tiendas, Bodegas)
CREATE TABLE IF NOT EXISTS audit_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  consecutive INTEGER GENERATED BY DEFAULT AS IDENTITY,
  location_id UUID REFERENCES warehouses(id) ON DELETE RESTRICT,
  location_name TEXT NOT NULL,
  audit_type TEXT NOT NULL DEFAULT 'Completo' CHECK (audit_type IN ('Completo', 'Parcial', 'Por Categoria', 'Por Referencia', 'Por Ubicacion', 'Muestreo', 'Ciclico')),
  status TEXT NOT NULL DEFAULT 'En Progreso' CHECK (status IN ('Borrador', 'En Progreso', 'En Revision', 'Justificado', 'Aprobado', 'Ajustado', 'Cerrado', 'Cancelado')),
  sample_percentage INTEGER DEFAULT 100,
  created_by TEXT NOT NULL,
  approved_by TEXT,
  total_expected_items INTEGER DEFAULT 0,
  total_expected_qty INTEGER DEFAULT 0,
  total_counted_qty INTEGER DEFAULT 0,
  total_missing_qty INTEGER DEFAULT 0,
  total_surplus_qty INTEGER DEFAULT 0,
  financial_impact NUMERIC DEFAULT 0, -- Pérdida/Ganancia estimada en $
  financial_missing NUMERIC DEFAULT 0,
  financial_surplus NUMERIC DEFAULT 0,
  reconciliation_rate NUMERIC DEFAULT 0, -- Porcentaje % de coincidencia
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Detalle de Auditoría por Producto (Esperado vs Contado vs Diferencia)
CREATE TABLE IF NOT EXISTS audit_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_id UUID REFERENCES audit_sessions(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  color_id UUID REFERENCES colors(id) ON DELETE SET NULL,
  size_id UUID REFERENCES sizes(id) ON DELETE SET NULL,
  sku_code TEXT NOT NULL,
  barcode TEXT,
  product_name TEXT NOT NULL,
  category_name TEXT DEFAULT 'Sin Categoría',
  color_name TEXT DEFAULT '—',
  size_code TEXT DEFAULT 'ST',
  expected_qty INTEGER NOT NULL DEFAULT 0,
  counted_qty INTEGER NOT NULL DEFAULT 0,
  difference_qty INTEGER GENERATED ALWAYS AS (counted_qty - expected_qty) STORED,
  unit_cost NUMERIC DEFAULT 0,
  unit_price NUMERIC DEFAULT 0,
  difference_cost NUMERIC DEFAULT 0,
  difference_price NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'OK' CHECK (status IN ('OK', 'Faltante', 'Sobrante', 'Ubicacion_Incorrecta', 'No_Registrado')),
  item_state TEXT DEFAULT 'Detectada' CHECK (item_state IN ('Detectada', 'En Revision', 'Justificada', 'Pendiente de Ajuste', 'Ajustada', 'Rechazada')),
  justification TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Registro de Lecturas/Escaneos Individuales (Alta velocidad con Pistola)
CREATE TABLE IF NOT EXISTS audit_scans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_id UUID REFERENCES audit_sessions(id) ON DELETE CASCADE,
  sku_code TEXT NOT NULL,
  barcode TEXT,
  counted_by TEXT NOT NULL,
  device_info TEXT DEFAULT 'Pistola Lectora USB/Bluetooth',
  scanned_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla de Productos No Registrados Encontrados Físicamente
CREATE TABLE IF NOT EXISTS audit_unregistered_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_id UUID REFERENCES audit_sessions(id) ON DELETE CASCADE,
  scanned_code TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  action_taken TEXT DEFAULT 'REGISTRADO_SOBRANTE' CHECK (action_taken IN ('REGISTRADO_SOBRANTE', 'CREADO', 'ASOCIADO', 'INCIDENCIA')),
  associated_product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  reported_by TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabla de Solicitudes de Ajuste de Inventario (Flujo Aprobación Jerárquica)
CREATE TABLE IF NOT EXISTS audit_adjustment_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  consecutive INTEGER GENERATED BY DEFAULT AS IDENTITY,
  audit_id UUID REFERENCES audit_sessions(id) ON DELETE CASCADE,
  requested_by TEXT NOT NULL,
  approved_by TEXT,
  status TEXT DEFAULT 'Pendiente' CHECK (status IN ('Pendiente', 'Aprobado', 'Rechazado')),
  total_items_to_adjust INTEGER DEFAULT 0,
  total_financial_impact NUMERIC DEFAULT 0,
  reason TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ
);

-- 6. Tabla de Bitácora Inmutable de Auditoría (Audit Log Timeline)
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_id UUID REFERENCES audit_sessions(id) ON DELETE CASCADE,
  action TEXT NOT NULL, -- 'CREACION', 'LECTURA_PISTOLA', 'DIFERENCIA_DETECTADA', 'JUSTIFICACION', 'SOLICITUD_AJUSTE', 'APROBACION', 'CIERRE'
  user_email TEXT NOT NULL,
  before_state JSONB DEFAULT '{}'::jsonb,
  after_state JSONB DEFAULT '{}'::jsonb,
  ip_address TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Indexación para búsquedas de alta velocidad con Pistola Escáner
CREATE INDEX IF NOT EXISTS idx_audit_items_audit_sku ON audit_items(audit_id, sku_code);
CREATE INDEX IF NOT EXISTS idx_audit_items_barcode ON audit_items(barcode);
CREATE INDEX IF NOT EXISTS idx_audit_scans_audit_id ON audit_scans(audit_id);
CREATE INDEX IF NOT EXISTS idx_audit_sessions_location ON audit_sessions(location_id);
CREATE INDEX IF NOT EXISTS idx_audit_sessions_status ON audit_sessions(status);

-- 7. Habilitar RLS y Permisos
ALTER TABLE audit_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_unregistered_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_adjustment_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_sessions' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON audit_sessions FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_items' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON audit_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_scans' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON audit_scans FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_unregistered_items' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON audit_unregistered_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_adjustment_requests' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON audit_adjustment_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'audit_logs' AND policyname = 'allow_authenticated') THEN
    CREATE POLICY allow_authenticated ON audit_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

GRANT ALL ON audit_sessions TO authenticated;
GRANT ALL ON audit_items TO authenticated;
GRANT ALL ON audit_scans TO authenticated;
GRANT ALL ON audit_unregistered_items TO authenticated;
GRANT ALL ON audit_adjustment_requests TO authenticated;
GRANT ALL ON audit_logs TO authenticated;

GRANT SELECT ON audit_sessions TO anon;
GRANT SELECT ON audit_items TO anon;
GRANT SELECT ON audit_scans TO anon;
GRANT SELECT ON audit_unregistered_items TO anon;
GRANT SELECT ON audit_adjustment_requests TO anon;
GRANT SELECT ON audit_logs TO anon;
